name: DevBukkit
main: com.cogito.bukkit.dev.DevBukkit
version: 0.1
commands:
  dev:
    description: Dev Commands
    usage: |        
        Incorrect usage of command /<command>. Examples:
           /<command> debug [on|off] - toggle full debug mode.
           /<command> debug kill - kill debug mode.
           /<command> eventName [on|off|default] - toggle event debug mode.
           /<command> events - list all supported events and their command aliases.
           /<command> god [on|off] - toggle god mode.