name: DevBukkit
main: com.cogito.bukkit.dev.DevBukkit
version: 0.1
commands:
  dev:
    description: Dev Commands
    usage: |        
        Incorrect usage of command /<command>. Examples:
           /<command> debug [on|off] - toggle full debug mode.
           /<command> god [on|off] - toggle god mode.